terminal:
  build: .
  volumes:
    - ./:/go/src/github.com/buildkite/terminal
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - TERMINAL_VERSION
